### ISSUE TITLE
failed when xsd to avsc

### ISSUE THREAD

**Issue by wanghaisheng** [stealthly/xml-avro#9]
I have a complex xsd file ,it include  another xsd .when I run the convert,the output is not well defined asvc format

**Comment by joestein** [comment]
Hi, can you provide something for us to reproduce the issue please? Also, if you have already solved it we would accept a pull request too.

Thanks!

**Comment by wanghaisheng** [comment]
definitely,I was tryint to transform one of the following xsd file,such as patient.xsd,which include 
fhir-base.xsd.
http://hl7-fhir.github.io/fhir-all-xsd.zip
what i get is really a mess

**Comment by dmitrypekar** [comment]
@wanghaisheng Hi. Please pull & rebuild. After that you will be able to use avro converter using following options:
`-d -b <fhirXsdDir> fhir-all.xsd <fhirXmlFile>`

Note: -d options enables debug, -b options sets base dir for resolving external refs inside schema.

I was able to convert successfully following xml:

```
<Patient>
    <identifier>
        <use value="usual"/>
        <label value="MRN"/>
        <system value="urn:oid:1.2.36.146.595.217.0.1"/>
        <value value="12345"/>
        <period>
            <start value="2001-05-06"/>
        </period>
        <assigner>
            <display value="Acme Healthcare"/>
        </assigner>
    </identifier>
</Patient>
```

**Comment by wanghaisheng** [comment]
thx for that
can u share me the idea how you fix this one

**Comment by dmitrypekar** [comment]
I've added a fix to the converter itself. It failed to generate schema for above xsds previously, because the schema contains recursive anonymous type definitions. I've changed the way the name of type is generated to use Xerces internal type's name. You can see this fix in my commit. 

Does it run successfully now for your files?

**Comment by wanghaisheng** [comment]
i dont get your hint  -d -b <fhirXsdDir> fhir-all.xsd <fhirXmlFile>
if i have only a xsd file,should I run the following
java -cp target/xml-avro*.jar   fhir-all-xsd/patient.xsd  patient.avsc
why do I need a <fhirXmlFile> param?
is this one should be a xsd to a avsc or avpr 
a xml to avro?

**Comment by dmitrypekar** [comment]
Currently CLI doesn't support generation of the schema only. You should provide both xsd + xml and you will get both avsc + avro.  But if you want you could use internal API programmaticaly to generate schema only.

**Comment by wanghaisheng** [comment]
do you mean this one ? do i need to populate each element and attribute defined in the xsd?
java -cp target/xml-avro*.jar fhir-all-xsd/patient.xsd patient.xml

**Comment by wanghaisheng** [comment]
> java -jar target/xml-avro*.jar -b fhir-all-xsd  patient.xsd patient-example-a.xml
> 
> ```
> Converting: 
> fhir-all-xsd/patient.xsd -> fhir-all-xsd/patient.avsc
> fhir-all-xsd/patient-example-a.xml -> fhir-all-xsd/patient-example-a.avro
> Exception in thread "main" ly.stealth.xmlavro.ConverterException: :file:///Users/wanghaisheng/workspace/xml-avro/patient.xsd:file:///Users/wanghaisheng/workspace/xml-avro/patient.xsd::252:35:14198:sch-props-correct.2: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'http://hl7.org/fhir,LinkType'.
>     at ly.stealth.xmlavro.SchemaBuilder$ErrorHandler.throwExceptionIfHasError(SchemaBuilder.java:397)
>     at ly.stealth.xmlavro.SchemaBuilder.createSchema(SchemaBuilder.java:98)
>     at ly.stealth.xmlavro.SchemaBuilder.createSchema(SchemaBuilder.java:83)
>     at ly.stealth.xmlavro.SchemaBuilder.createSchema(SchemaBuilder.java:68)
>     at ly.stealth.xmlavro.Converter.main(Converter.java:129)
> Caused by: :file:///Users/wanghaisheng/workspace/xml-avro/patient.xsd:file:///Users/wanghaisheng/workspace/xml-avro/patient.xsd::252:35:14198:sch-props-correct.2: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'http://hl7.org/fhir,LinkType'.
>     at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
>     at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
>     at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
>     at org.apache.xerces.impl.xs.traversers.XSDHandler.checkForDuplicateNames(Unknown Source)
>     at org.apache.xerces.impl.xs.traversers.XSDHandler.buildGlobalNameRegistries(Unknown Source)
>     at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
>     at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
>     at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
>     at org.apache.xerces.impl.xs.XMLSchemaLoader.load(Unknown Source)
>     at ly.stealth.xmlavro.SchemaBuilder.createSchema(SchemaBuilder.java:96)
>     ... 3 more
> ```
> 
> I place the   patient-example-a.xml  under fhir-all-xsd
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Patient xmlns="http://hl7.org/fhir">
>   <id value="pat1"/>
>   <text>
>     <status value="generated"/>
>     <div xmlns="http://www.w3.org/1999/xhtml">
>       <p>Patient Donald DUCK @ Acme Healthcare, Inc. MR = 654321</p>
>     </div>
>   </text>
>   <identifier>
>     <use value="usual"/>
>     <label value="MRN"/>
>     <system value="urn:oid:0.1.2.3.4.5.6.7"/>
>     <value value="654321"/>
>   </identifier>
>   <name>
>     <use value="official"/>
>     <family value="Donald"/>
>     <given value="Duck"/>
>   </name>
>   <gender value="male"/>
>   <photo>
>     <contentType value="image/gif"/>
>     <data value="R0lGODlhEwARAPcAAAAAAAAA/+9aAO+1AP/WAP/eAP/eCP/eEP/eGP/nAP/nCP/nEP/nIf/nKf/nUv/nWv/vAP/vCP/vEP/vGP/vIf/vKf/vMf/vOf/vWv/vY//va//vjP/3c//3lP/3nP//tf7"/>
>   </photo>
>   <contact>
>     <relationship>
>       <coding>
>         <system value="http://hl7.org/fhir/patient-contact-relationship"/>
>         <code value="owner"/>
>       </coding>
>     </relationship>
>     <organization>
>       <reference value="Organization/1"/>
>       <display value="Walt Disney Corporation"/>
>     </organization>
>   </contact>
>   <managingOrganization>
>     <reference value="Organization/1"/>
>     <display value="ACME Healthcare, Inc"/>
>   </managingOrganization>
>   <link>
>     <other>
>       <reference value="Patient/pat2"/>
>     </other>
>     <type value="seealso"/>
>   </link>
>   <active value="true"/>
> </Patient>
> ```

**Comment by dmitrypekar** [comment]
You should use fhir-all.xsd as a schema file. It includes rest of the xsd files.
Try this one:
`java -jar target/xml-avro*.jar -b fhir-all-xsd fhir-all.xsd patient-example-a.xml`

Also make sure, that patient-example-a.xml is valid according to xsd schema.

**Comment by wanghaisheng** [comment]
i am sure it is valid 
java -jar target/xml-avro*.jar -b fhir-all-xsd fhir-all.xsd patient-example-a.xml
Converting: 
fhir-all-xsd/fhir-all.xsd -> fhir-all-xsd/fhir-all.avsc
fhir-all-xsd/patient-example-a.xml -> fhir-all-xsd/patient-example-a.avro
Exception in thread "main" java.lang.StackOverflowError
    at java.util.HashMap.inflateTable(HashMap.java:317)
    at java.util.HashMap.put(HashMap.java:488)
    at org.apache.avro.Schema$UnionSchema.<init>(Schema.java:785)
    at org.apache.avro.Schema.createUnion(Schema.java:167)
    at ly.stealth.xmlavro.SchemaBuilder.createTypeSchema(SchemaBuilder.java:162)
    at ly.stealth.xmlavro.SchemaBuilder.createField(SchemaBuilder.java:284)
    at ly.stealth.xmlavro.SchemaBuilder.createFields(SchemaBuilder.java:219)
    at ly.stealth.xmlavro.SchemaBuilder.createRecordSchema(SchemaBuilder.java:206)

**Comment by dmitrypekar** [comment]
Looks like you are using previous build. Please update your repo, create last build and try again.

**Comment by wanghaisheng** [comment]
it works now

**Comment by wanghaisheng** [comment]
can u compiling the schema fhir-all.avsc to java class using org.apache.avro ?

**Comment by dmitrypekar** [comment]
probably, should be possible, but I didn't tried that.

**Comment by Shafi863** [comment]
hi wanghaisheng, 
how to generate xsd file  from XML. i am using tang.jar it is nor working. 
cloud you please tell me the steps to generate the avsc and avro file from xml.
thank you.

**Comment by wanghaisheng** [comment]
i don`t know how to  generate xsd file from xml file in programming language now ,but it  could be done with OxygenXML Editor .
as author says " You should provide both xsd + xml and you will get both avsc + avro"
under your specified directory ,you can run the following command:
java -jar target/xml-avro*.jar -b fhir-all-xsd fhir-all.xsd patient-example-a.xml

my files are like this 

```
root directory
-fhir-all-xsd
--fhir-all.xsd
patient-example-a.xml
```

you can change a bit according to your files
